services:

  scraperr_api:
    init: True
    image: alyxfranck/scraperr_api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://scraperr_api:8000 # your API URL
      - SERVER_URL=http://scraperr_api:8000 # your docker container API URL
      - LOG_LEVEL=INFO
      - SECRET_KEY=your_secret_key # used to encode authentication tokens (can be a random string)
      - ALGORITHM=HS256 # authentication encoding algorithm
      - ACCESS_TOKEN_EXPIRE_MINUTES=600 # access token expire minutes
    container_name: scraperr_api
    ports:
      - 8000:8000
    volumes:
      - "$PWD/data:/project/data"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
networks:
  web:
